# Generated by Django 5.2.13 on 2026-04-24 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('algorithms', 'Algorithms'), ('ds', 'Data Structures'), ('systems', 'Systems'), ('webdev', 'Web Development'), ('aiml', 'AI/ML')], max_length=50)),
                ('difficulty', models.IntegerField(default=1)),
                ('xp_required_to_unlock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SkillPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_edges', to='skills.skill')),
                ('to_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_edges', to='skills.skill')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='prerequisites',
            field=models.ManyToManyField(related_name='unlocks', through='skills.SkillPrerequisite', to='skills.skill'),
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='skills.skill')),
            ],
        ),
    ]
