# Generated by Django 5.2.13 on 2026-04-24 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skillprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='skillprerequisite',
            unique_together={('from_skill', 'to_skill')},
        ),
        migrations.AddIndex(
            model_name='skillprogress',
            index=models.Index(fields=['user', 'status'], name='skills_skil_user_id_179cd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillprogress',
            unique_together={('user', 'skill')},
        ),
    ]
