# Generated by Django 5.2.13 on 2026-04-30 11:03

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_add_depth_and_quest_stub_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text="Model name: 'skill', 'quest', 'questsubmission', etc.", max_length=50)),
                ('object_id', models.IntegerField(help_text='PK of the relational record that was embedded.')),
                ('collection_name', models.CharField(choices=[('skill_knowledge', 'Skill Knowledge'), ('code_patterns', 'Code Patterns'), ('ai_code_samples', 'AI Code Samples')], max_length=50)),
                ('chroma_id', models.CharField(help_text='The ID used in ChromaDB for this document.', max_length=200)),
                ('embedded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA-256 of the embedded text. Used to detect stale embeddings.', max_length=64)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='skill',
            name='skill_depth_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedskilltree',
            new_name='gst_user_status_idx',
            old_name='skills_gene_created_8278e2_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedskilltree',
            new_name='gst_public_status_idx',
            old_name='skills_gene_is_publ_57ab09_idx',
        ),
        migrations.RenameIndex(
            model_name='skillprogress',
            new_name='skillprog_user_status_idx',
            old_name='skills_skil_user_id_179cd7_idx',
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skillprerequisite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='generatedskilltree',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='generatedskilltree',
            name='topic',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='difficulty',
            field=models.IntegerField(default=1, help_text='1 (beginner) to 5 (expert)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tree_depth',
            field=models.IntegerField(default=0, help_text='Depth level in DAG (0 = root)'),
        ),
        migrations.AlterField(
            model_name='skillprogress',
            name='attempts_count',
            field=models.IntegerField(default=0, help_text='Denormalized: total quest attempts for this skill'),
        ),
        migrations.AlterField(
            model_name='skillprogress',
            name='quest_completion_count',
            field=models.IntegerField(default=0, help_text='Denormalized: quests passed for this skill'),
        ),
        migrations.AlterField(
            model_name='skillprogress',
            name='time_spent_minutes',
            field=models.IntegerField(default=0, help_text='Denormalized: total time spent on this skill'),
        ),
        migrations.AlterField(
            model_name='usercurriculum',
            name='total_quests',
            field=models.IntegerField(default=0, help_text='Denormalized: recompute from weeks JSON if needed'),
        ),
        migrations.AddIndex(
            model_name='generatedskilltree',
            index=models.Index(fields=['-created_at'], name='gst_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'difficulty'], name='skill_cat_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['tree_depth', 'difficulty'], name='skill_depth_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['-created_at'], name='skill_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='skillprerequisite',
            index=models.Index(fields=['from_skill', 'to_skill'], name='skillprereq_edge_idx'),
        ),
        migrations.AddIndex(
            model_name='skillprogress',
            index=models.Index(fields=['user', 'completed_at'], name='skillprog_user_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='usercurriculum',
            index=models.Index(fields=['user', '-created_at'], name='curriculum_user_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddingrecord',
            index=models.Index(fields=['content_type', 'object_id'], name='embedding_object_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddingrecord',
            index=models.Index(fields=['collection_name', 'updated_at'], name='embedding_collection_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='embeddingrecord',
            unique_together={('content_type', 'object_id', 'collection_name')},
        ),
    ]
