# Generated by Django 6.0.4 on 2026-07-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_embeddingrecord_remove_skill_skill_depth_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='courses',
            field=models.JSONField(blank=True, default=list, help_text='Up to 5 recommended courses fetched from Coursera and Udemy via Apify. Each entry: {title, provider, url, price, rating, instructor}'),
        ),
    ]
