# Generated by Django 6.0.4 on 2026-04-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_generatedskilltree'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='generatedskilltree',
            new_name='skills_gene_created_8278e2_idx',
            old_name='skills_gene_created_idx',
        ),
        migrations.RenameIndex(
            model_name='generatedskilltree',
            new_name='skills_gene_is_publ_57ab09_idx',
            old_name='skills_gene_is_publ_idx',
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
