# Generated by Django 6.0.4 on 2026-07-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_add_courses_to_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='generatedskilltree',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='generatedskilltree',
            name='nodes_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedskilltree',
            name='outline',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generatedskilltree',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='generatedskilltree',
            name='total_nodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='estimated_minutes',
            field=models.IntegerField(default=60, help_text='Estimated learning time for this node'),
        ),
        migrations.AddField(
            model_name='skill',
            name='free_resources',
            field=models.JSONField(blank=True, default=list, help_text='Free learning resources fetched via SERP API. Each entry: {title, url, type, source, snippet}'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skills_gained',
            field=models.JSONField(blank=True, default=list, help_text='List of skill names gained on completion'),
        ),
        migrations.AddField(
            model_name='skill',
            name='xp_reward',
            field=models.IntegerField(default=100, help_text='XP awarded when this node is completed'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='courses',
            field=models.JSONField(blank=True, default=list, help_text='Recommended paid courses fetched from Coursera and Udemy via Apify. Each entry: {title, provider, url, price, rating, instructor, duration, thumbnail}'),
        ),
    ]
