# Generated by Django 5.2.13 on 2026-04-28 11:17

from django.db import migrations

def populate_skills(apps, schema_editor):
    Skill = apps.get_model('skills', 'Skill')
    SkillPrerequisite = apps.get_model('skills', 'SkillPrerequisite')

    skills_data = [
        # Algorithms Category
        {"title": "Binary Search", "description": "Master the art of efficient searching in sorted arrays using the divide-and-conquer approach.", "category": "algorithms", "difficulty": 2, "xp_required_to_unlock": 0},
        {"title": "Sorting Algorithms", "description": "Learn fundamental sorting algorithms including bubble sort, insertion sort, and selection sort.", "category": "algorithms", "difficulty": 2, "xp_required_to_unlock": 50},
        {"title": "QuickSort & MergeSort", "description": "Advanced sorting algorithms with O(n log n) complexity. Essential for technical interviews.", "category": "algorithms", "difficulty": 3, "xp_required_to_unlock": 150},
        {"title": "Dynamic Programming", "description": "Solve complex problems by breaking them down into simpler subproblems. Master memoization and tabulation.", "category": "algorithms", "difficulty": 4, "xp_required_to_unlock": 300},
        
        # Data Structures Category
        {"title": "Arrays & Lists", "description": "Foundation of data structures. Learn array manipulation, traversal, and common operations.", "category": "ds", "difficulty": 1, "xp_required_to_unlock": 0},
        {"title": "Linked Lists", "description": "Master singly and doubly linked lists. Learn insertion, deletion, and reversal operations.", "category": "ds", "difficulty": 2, "xp_required_to_unlock": 100},
        {"title": "Stacks & Queues", "description": "LIFO and FIFO data structures. Essential for BFS, DFS, and expression evaluation.", "category": "ds", "difficulty": 2, "xp_required_to_unlock": 100},
        {"title": "Binary Trees", "description": "Hierarchical data structures. Learn traversals, BST operations, and tree properties.", "category": "ds", "difficulty": 3, "xp_required_to_unlock": 200},
        {"title": "Graph Theory", "description": "Master graph representations, traversals (BFS/DFS), and shortest path algorithms.", "category": "ds", "difficulty": 4, "xp_required_to_unlock": 350},
        
        # Systems Category
        {"title": "Operating Systems Basics", "description": "Understand processes, threads, memory management, and file systems.", "category": "systems", "difficulty": 2, "xp_required_to_unlock": 0},
        {"title": "Computer Networks", "description": "Learn TCP/IP, HTTP, DNS, and network protocols. Essential for backend development.", "category": "systems", "difficulty": 3, "xp_required_to_unlock": 150},
        {"title": "Database Systems", "description": "Master SQL, database design, indexing, and query optimization.", "category": "systems", "difficulty": 3, "xp_required_to_unlock": 200},
        
        # Web Dev Category
        {"title": "HTML & CSS", "description": "Foundation of web development. Learn semantic HTML and modern CSS techniques.", "category": "webdev", "difficulty": 1, "xp_required_to_unlock": 0},
        {"title": "JavaScript Fundamentals", "description": "Master ES6+, async/await, promises, and modern JavaScript features.", "category": "webdev", "difficulty": 2, "xp_required_to_unlock": 100},
        {"title": "React Development", "description": "Build modern web applications with React. Learn hooks, state management, and component patterns.", "category": "webdev", "difficulty": 3, "xp_required_to_unlock": 250},
        {"title": "REST API Development", "description": "Design and build RESTful APIs. Learn authentication, validation, and best practices.", "category": "webdev", "difficulty": 3, "xp_required_to_unlock": 250},
        
        # AI/ML Category
        {"title": "Python Programming", "description": "Master Python fundamentals, data structures, and object-oriented programming.", "category": "aiml", "difficulty": 1, "xp_required_to_unlock": 0},
        {"title": "NumPy & Pandas", "description": "Data manipulation and analysis with Python. Essential for data science and ML.", "category": "aiml", "difficulty": 2, "xp_required_to_unlock": 100},
        {"title": "Machine Learning Basics", "description": "Learn supervised and unsupervised learning. Master regression, classification, and clustering.", "category": "aiml", "difficulty": 3, "xp_required_to_unlock": 300},
        {"title": "Deep Learning", "description": "Neural networks, CNNs, RNNs, and transformers. Build AI models with PyTorch or TensorFlow.", "category": "aiml", "difficulty": 4, "xp_required_to_unlock": 500},
    ]

    skill_objects = {}
    for data in skills_data:
        skill, created = Skill.objects.get_or_create(title=data['title'], defaults=data)
        skill_objects[data['title']] = skill

    prerequisites_data = [
        ("Arrays & Lists", "Binary Search"),
        ("Arrays & Lists", "Sorting Algorithms"),
        ("Sorting Algorithms", "QuickSort & MergeSort"),
        ("QuickSort & MergeSort", "Dynamic Programming"),
        ("Arrays & Lists", "Linked Lists"),
        ("Arrays & Lists", "Stacks & Queues"),
        ("Linked Lists", "Binary Trees"),
        ("Binary Trees", "Graph Theory"),
        ("Stacks & Queues", "Graph Theory"),
        ("Operating Systems Basics", "Computer Networks"),
        ("Operating Systems Basics", "Database Systems"),
        ("HTML & CSS", "JavaScript Fundamentals"),
        ("JavaScript Fundamentals", "React Development"),
        ("JavaScript Fundamentals", "REST API Development"),
        ("Python Programming", "NumPy & Pandas"),
        ("NumPy & Pandas", "Machine Learning Basics"),
        ("Machine Learning Basics", "Deep Learning"),
        ("Arrays & Lists", "Python Programming"),
        ("Database Systems", "REST API Development"),
    ]

    for from_title, to_title in prerequisites_data:
        from_skill = skill_objects.get(from_title)
        to_skill = skill_objects.get(to_title)
        if from_skill and to_skill:
            SkillPrerequisite.objects.get_or_create(from_skill=from_skill, to_skill=to_skill)

def reverse_populate_skills(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_rename_skills_gene_created_idx_skills_gene_created_8278e2_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_skills, reverse_populate_skills),
    ]
