# Generated by Django 5.2.13 on 2026-04-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('streak_days', models.IntegerField()),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank'],
                'get_latest_by': 'snapshot_at',
            },
        ),
    ]
