# Generated by Django 6.0.4 on 2026-04-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_leaderboardsnapshot_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leaderboardsnapshot',
            name='leaderboard_user_snap_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaderboardsnapshot',
            name='leaderboard_snap_at_idx',
        ),
    ]
