# Generated by Django 5.2.13 on 2026-04-28 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_remove_leaderboardsnapshot_leaderboard_user_snap_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leaderboardsnapshot',
            index=models.Index(fields=['user', 'snapshot_at'], name='leaderboard_user_snap_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardsnapshot',
            index=models.Index(fields=['-snapshot_at'], name='leaderboard_snap_at_idx'),
        ),
    ]
