import re
import os

with open(r'c:\personal project\skilltree-ai\backend\scripts\populate_quests.py', 'r', encoding='utf-8') as f:
    code = f.read()

# Make transformations
code = code.replace('from skills.models import Skill\n', '')
code = code.replace('from quests.models import Quest\n', '')
code = code.replace('Quest.objects.all().delete()', '# Quest.objects.all().delete()')

# We can replace Quest.objects.create with safe_create
code = code.replace('Quest.objects.create(', 'safe_create(')

# Indent everything by 4 spaces
indented_code = '\n'.join('    ' + line if line else line for line in code.split('\n'))

with open(r'c:\personal project\skilltree-ai\backend\quests\migrations\0007_populate_quests.py', 'r', encoding='utf-8') as f:
    empty_mig = f.read()

deps_match = re.search(r'dependencies = \[.*?\]', empty_mig, re.DOTALL)
deps = deps_match.group(0) if deps_match else "dependencies = []"

final_code = f"""# Generated by Django 5.2.13 on 2026-04-28 11:18

from django.db import migrations

def populate_quests(apps, schema_editor):
    Quest = apps.get_model('quests', 'Quest')
    Skill = apps.get_model('skills', 'Skill')

    def safe_create(**kwargs):
        title = kwargs.pop('title')
        Quest.objects.get_or_create(title=title, defaults=kwargs)

{indented_code}

def reverse_populate_quests(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    {deps}

    operations = [
        migrations.RunPython(populate_quests, reverse_populate_quests),
    ]
"""

with open(r'c:\personal project\skilltree-ai\backend\quests\migrations\0007_populate_quests.py', 'w', encoding='utf-8') as f:
    f.write(final_code)

print("Conversion complete.")
