# Generated by Django 5.2.13 on 2026-04-25 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0003_initial'),
        ('skills', '0003_usercurriculum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('lesson', 'Lesson'), ('tip', 'Tip'), ('example', 'Example'), ('reference', 'Reference')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Markdown formatted content')),
                ('code_example', models.TextField(blank=True, default='')),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('java', 'Java'), ('go', 'Go'), ('sql', 'SQL'), ('html', 'HTML'), ('css', 'CSS'), ('markdown', 'Markdown')], default='python', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ai_reviewed', 'AI Reviewed'), ('published', 'Published')], default='draft', max_length=20)),
                ('ai_review_notes', models.TextField(blank=True, default='', help_text='LM Studio review output')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_content', to='skills.skill')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['skill', 'status'], name='admin_panel_skill_i_dd10d8_idx'), models.Index(fields=['status'], name='admin_panel_status_b65420_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('code', 'Code Challenge'), ('mcq', 'Multiple Choice'), ('open_ended', 'Open Ended')], max_length=20)),
                ('prompt', models.TextField(help_text='Question text or coding challenge description')),
                ('correct_answer', models.TextField(help_text='For MCQ: correct option. For code: model solution.')),
                ('mcq_options', models.JSONField(blank=True, default=list, help_text='Array of options for MCQ')),
                ('test_cases', models.JSONField(default=list, help_text='Array of test cases: [{input, expected_output, description}]')),
                ('validation_criteria', models.TextField(help_text='Natural language criteria for LM Studio to check')),
                ('points', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='quests.quest')),
            ],
            options={
                'ordering': ['quest', '-created_at'],
                'indexes': [models.Index(fields=['quest', 'question_type'], name='admin_panel_quest_i_df0ad1_idx')],
            },
        ),
    ]
