# Generated by Django 5.2.13 on 2026-04-26 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('java', 'Java'), ('go', 'Go')], default='python', help_text='Programming language for code challenges', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentquestion',
            name='validation_criteria',
            field=models.TextField(blank=True, default='', help_text='Natural language criteria for LM Studio to check'),
        ),
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(help_text='User submitted answer or code')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('evaluating', 'Evaluating'), ('evaluated', 'Evaluated'), ('error', 'Error')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict, help_text='Evaluation result from AssessmentEngine')),
                ('score', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(blank=True, help_text='Whether submission passed evaluation', null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='admin_panel.assessmentquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', 'question'], name='admin_panel_user_id_9ebc1e_idx'), models.Index(fields=['status'], name='admin_panel_status_62e496_idx'), models.Index(fields=['-submitted_at'], name='admin_panel_submitt_1e115b_idx')],
            },
        ),
    ]
