# Generated by Django 5.2.13 on 2026-04-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_hint_usage'),
        ('mentor', '0002_initial'),
    ]

    operations = [
    ]
