# Generated by Django 5.2.13 on 2026-04-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_merge_0002_hint_usage_0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hintusage',
            new_name='mentor_hint_user_id_3e2356_idx',
            old_name='mentor_hintusage_user_quest_idx',
        ),
        migrations.RenameIndex(
            model_name='hintusage',
            new_name='mentor_hint_user_id_b2b8ae_idx',
            old_name='mentor_hintusage_user_requested_idx',
        ),
    ]
