# Generated by Django 5.2.13 on 2026-04-30 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_rename_mentor_hintusage_user_quest_idx_mentor_hint_user_id_3e2356_idx_and_more'),
        ('quests', '0011_remove_solutioncomment_quests_solu_solutio_5093d8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hintusage',
            name='mentor_hint_user_id_3e2356_idx',
        ),
        migrations.RemoveIndex(
            model_name='hintusage',
            name='mentor_hint_user_id_b2b8ae_idx',
        ),
        migrations.AddIndex(
            model_name='aiinteraction',
            index=models.Index(fields=['user', 'interaction_type', '-created_at'], name='aiinteraction_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinteraction',
            index=models.Index(fields=['interaction_type', 'created_at'], name='aiinteraction_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='hintusage',
            index=models.Index(fields=['user', 'quest', 'requested_at'], name='hintusage_user_quest_date_idx'),
        ),
        migrations.AddIndex(
            model_name='hintusage',
            index=models.Index(fields=['user', '-requested_at'], name='hintusage_user_history_idx'),
        ),
    ]
