"""
Seed Quests — SkillTree AI
==============================
100 deterministic quests across 10 quest families, each mapped to exactly one skill.
"""

# Each quest: (title, skill_index, family, type, difficulty, xp, est_minutes, description, prereq_quest_indices)
# skill_index references SKILLS[] in seed_skills.py

QUESTS = [
    # ── Family: data_structures (0-9) ────────────────────────────────────────
    ("Traverse and Sum Array", 0, "data_structures", "coding", 1, 50, 15,
     "Given an array of integers, return the sum of all elements.\n\nExample:\n  Input: 1 2 3 4 5\n  Output: 15", []),
    ("Reverse String In-Place", 1, "data_structures", "coding", 1, 50, 15,
     "Reverse a string without using built-in reverse methods.\n\nExample:\n  Input: hello\n  Output: olleh", []),
    ("Two Sum with Two Pointers", 2, "data_structures", "coding", 2, 100, 20,
     "Given a sorted array and target, find two numbers that add up to target using two pointers.\n\nExample:\n  Input: 1 2 3 4 6 → target=6\n  Output: [1, 3]", [0]),
    ("Insert into Linked List", 3, "data_structures", "coding", 2, 100, 25,
     "Insert a value at a given position in a singly linked list and return the head.\n\nExample:\n  Input: 1->2->4, pos=2, val=3\n  Output: 1->2->3->4", []),
    ("Reverse Linked List", 3, "data_structures", "coding", 2, 120, 25,
     "Reverse a singly linked list iteratively and return the new head.\n\nExample:\n  Input: 1 2 3 4 5\n  Output: 5 4 3 2 1", [3]),
    ("Valid Parentheses", 5, "data_structures", "coding", 2, 100, 20,
     "Given a string of brackets, determine if every open bracket is closed correctly.\n\nExample:\n  Input: ()[]{}\n  Output: True", []),
    ("Implement Queue with Stacks", 6, "data_structures", "coding", 2, 120, 25,
     "Implement a FIFO queue using two LIFO stacks with enqueue and dequeue.\n\nExample:\n  enqueue(1), enqueue(2), dequeue() → 1", [5]),
    ("Validate BST", 7, "data_structures", "coding", 3, 175, 30,
     "Given a binary tree, determine if it is a valid binary search tree.\n\nExample:\n  Input: [2,1,3]\n  Output: True", []),
    ("Level Order Traversal", 8, "data_structures", "coding", 3, 175, 30,
     "Return the level-order traversal of a binary tree as nested lists.\n\nExample:\n  Input: [3,9,20,null,null,15,7]\n  Output: [[3],[9,20],[15,7]]", [7]),
    ("Detect Cycle in Graph", 10, "data_structures", "coding", 4, 275, 40,
     "Given a directed graph, detect if it contains a cycle using DFS.\n\nExample:\n  Input: edges=[[0,1],[1,2],[2,0]]\n  Output: True", [8]),

    # ── Family: algorithms (10-19) ───────────────────────────────────────────
    ("Implement Bubble Sort", 11, "algorithms", "coding", 1, 50, 15,
     "Sort an array using bubble sort and return the sorted result.\n\nExample:\n  Input: 5 3 1 4 2\n  Output: [1, 2, 3, 4, 5]", []),
    ("Merge Two Sorted Arrays", 12, "algorithms", "coding", 2, 100, 20,
     "Merge two sorted arrays into one sorted array.\n\nExample:\n  Input: [1,3,5] [2,4,6]\n  Output: [1,2,3,4,5,6]", [10]),
    ("Quick Sort Partition", 13, "algorithms", "coding", 3, 175, 30,
     "Implement the partition step of quicksort using Lomuto scheme.\n\nExample:\n  Input: [3,6,8,10,1,2,1]\n  Output: partitioned around pivot", [11]),
    ("Classic Binary Search", 14, "algorithms", "coding", 2, 100, 20,
     "Search for a target in a sorted array. Return index or -1.\n\nExample:\n  Input: [-1,0,3,5,9,12] target=9\n  Output: 4", []),
    ("Search Rotated Array", 15, "algorithms", "coding", 3, 175, 35,
     "Search for a target in a rotated sorted array in O(log n).\n\nExample:\n  Input: [4,5,6,7,0,1,2] target=0\n  Output: 4", [13]),
    ("Fibonacci with Memoization", 18, "algorithms", "coding", 3, 175, 25,
     "Compute the Nth Fibonacci number using top-down memoization.\n\nF(0)=0, F(1)=1\n\nExample:\n  Input: 10\n  Output: 55", []),
    ("Climbing Stairs DP", 19, "algorithms", "coding", 4, 275, 35,
     "Count distinct ways to climb N stairs taking 1 or 2 steps at a time using tabulation.\n\nExample:\n  Input: 5\n  Output: 8", [15]),
    ("Coin Change DP", 19, "algorithms", "coding", 4, 275, 40,
     "Find the minimum number of coins to make a given amount.\n\nExample:\n  Input: coins=[1,5,10], amount=11\n  Output: 2", [16]),
    ("Activity Selection", 20, "algorithms", "coding", 3, 175, 30,
     "Select the maximum number of non-overlapping activities using greedy.\n\nExample:\n  Input: starts=[1,3,0,5] ends=[2,4,6,7]\n  Output: 3", []),
    ("Fractional Knapsack", 21, "algorithms", "coding", 4, 275, 40,
     "Maximize value in a knapsack allowing fractional items using greedy.\n\nExample:\n  Input: weights=[10,20,30] values=[60,100,120] capacity=50\n  Output: 240.0", [18]),

    # ── Family: aiml (20-29) ─────────────────────────────────────────────────
    ("Train Linear Regression", 22, "aiml", "coding", 1, 50, 20,
     "Train a linear regression model on a simple dataset and print the R² score.\n\nUse scikit-learn.", []),
    ("K-Means Clustering", 23, "aiml", "coding", 2, 100, 25,
     "Apply K-Means to cluster a 2D dataset into K groups. Print cluster centers.\n\nUse scikit-learn.", [20]),
    ("Normalize Feature Matrix", 24, "aiml", "coding", 2, 100, 20,
     "Apply min-max normalization to a feature matrix. Handle missing values first.", [20]),
    ("Recursive Feature Elimination", 25, "aiml", "coding", 3, 175, 35,
     "Use RFE to select the top-K features from a dataset and print their names.", [22]),
    ("K-Fold Cross Validation", 26, "aiml", "coding", 2, 100, 25,
     "Evaluate a classifier with 5-fold cross-validation. Print mean accuracy.", [20]),
    ("Confusion Matrix Analysis", 27, "aiml", "coding", 3, 175, 30,
     "Generate a confusion matrix and compute precision, recall, and F1 score.", [24]),
    ("Build Neural Network", 28, "aiml", "coding", 3, 175, 40,
     "Build a 2-layer feedforward network with PyTorch for binary classification.", [25]),
    ("Image Classification CNN", 29, "aiml", "coding", 4, 275, 50,
     "Build a CNN to classify MNIST digits. Achieve >95% test accuracy.", [26]),
    ("Design Few-Shot Prompt", 30, "aiml", "coding", 2, 100, 20,
     "Design a few-shot prompt for sentiment classification. Test with 5 examples.", []),
    ("Build RAG Pipeline", 31, "aiml", "coding", 4, 275, 50,
     "Build a retrieval-augmented generation pipeline with ChromaDB and an LLM.", [28]),

    # ── Family: webdev (30-39) ───────────────────────────────────────────────
    ("Build Semantic Page", 33, "webdev", "coding", 1, 50, 15,
     "Create an HTML page using semantic elements: header, nav, main, article, footer.", []),
    ("Flexbox Card Layout", 34, "webdev", "coding", 1, 50, 20,
     "Build a responsive card grid using CSS Flexbox with gap and wrap.", []),
    ("Animate Modal Entrance", 35, "webdev", "coding", 2, 100, 25,
     "Create a modal dialog with CSS keyframe entrance animation and backdrop.", [30, 31]),
    ("Dynamic List Builder", 36, "webdev", "coding", 2, 100, 20,
     "Use DOM manipulation to add, remove, and filter items in a dynamic list.", [30]),
    ("Debounced Search Input", 37, "webdev", "coding", 2, 120, 25,
     "Implement a search input with debounced event handling (300ms delay).", [33]),
    ("React Todo App", 38, "webdev", "coding", 3, 175, 35,
     "Build a Todo application with React hooks: useState, useEffect, and useRef.", [34]),
    ("React Context Theme", 39, "webdev", "coding", 3, 175, 35,
     "Implement a dark/light theme toggle using React Context API and useReducer.", [35]),
    ("Django REST Endpoint", 40, "webdev", "coding", 3, 175, 30,
     "Create a Django REST Framework API endpoint with ModelSerializer and ViewSet.", []),
    ("JWT Auth Flow", 41, "webdev", "coding", 3, 175, 35,
     "Implement JWT login and token refresh endpoints with SimpleJWT in Django.", [37]),
    ("Full-Stack CRUD App", 43, "webdev", "coding", 4, 275, 50,
     "Build a React + Django CRUD application with auth, CORS, and token refresh.", [36, 38]),

    # ── Family: databases (40-49) ────────────────────────────────────────────
    ("Write SELECT Queries", 44, "databases", "coding", 1, 50, 15,
     "Write SELECT queries with WHERE, ORDER BY, and COUNT/SUM aggregates.", []),
    ("Multi-Table JOINs", 45, "databases", "coding", 2, 100, 25,
     "Write queries joining 3+ tables with INNER and LEFT JOINs.", [40]),
    ("Window Functions", 46, "databases", "coding", 3, 175, 30,
     "Use CTEs and window functions (ROW_NUMBER, RANK) for complex reporting.", [41]),
    ("Design Normalized Schema", 47, "databases", "coding", 2, 100, 25,
     "Design a 3NF schema for a library system with books, authors, and loans.", [40]),
    ("Draw ER Diagram", 48, "databases", "coding", 2, 100, 20,
     "Create an ER diagram with entities, relationships, and cardinality constraints.", [43]),
    ("Create Composite Index", 49, "databases", "coding", 3, 175, 25,
     "Add composite indexes to optimize a slow multi-column query.", [41]),
    ("Optimize Query Cache", 50, "databases", "coding", 4, 275, 40,
     "Design covering indexes and analyze EXPLAIN output to eliminate seq scans.", [45]),
    ("Transaction Rollback Handler", 51, "databases", "coding", 3, 175, 30,
     "Implement a transaction with savepoints and proper rollback on error.", [42]),
    ("Fix Deadlock Scenario", 52, "databases", "debugging", 4, 275, 45,
     "Debug and resolve a database deadlock between two concurrent transactions.", [47]),
    ("Tune Connection Pool", 54, "databases", "coding", 5, 400, 50,
     "Configure PgBouncer pool sizing and analyze connection wait metrics.", [46]),

    # ── Family: sysdesign (50-59) ────────────────────────────────────────────
    ("Design Load Balancer", 56, "sysdesign", "coding", 2, 100, 25,
     "Implement a round-robin load balancer that distributes requests across servers.", []),
    ("Implement CDN Cache", 57, "sysdesign", "coding", 2, 100, 25,
     "Set Cache-Control headers and implement cache invalidation for static assets.", []),
    ("Build Redis Cache Layer", 58, "sysdesign", "coding", 3, 175, 35,
     "Add a Redis caching layer to a Django view with TTL and cache invalidation.", [51]),
    ("Build Queue Worker", 59, "sysdesign", "coding", 2, 100, 30,
     "Create a Celery task queue worker that processes background jobs reliably.", []),
    ("Event Bus Design", 60, "sysdesign", "coding", 4, 275, 45,
     "Design an event-driven system with pub/sub message routing and dead letters.", [53]),
    ("WebSocket Chat Server", 61, "sysdesign", "coding", 3, 175, 40,
     "Build a real-time chat server using Django Channels and WebSockets.", [53]),
    ("Scale WebSocket Rooms", 62, "sysdesign", "coding", 4, 275, 45,
     "Scale WebSocket chat to multiple workers using Redis channel layer.", [55]),
    ("Prometheus Metrics", 63, "sysdesign", "coding", 2, 100, 25,
     "Instrument a Django app with Prometheus counters, histograms, and gauges.", []),
    ("Add Distributed Traces", 64, "sysdesign", "coding", 4, 275, 45,
     "Add OpenTelemetry tracing across two microservices with Jaeger backend.", [57]),
    ("Implement Rate Limiter", 65, "sysdesign", "coding", 3, 175, 30,
     "Build a token-bucket rate limiter middleware for a Django REST API.", [50]),

    # ── Family: devops (60-69) ───────────────────────────────────────────────
    ("Git Feature Branch Flow", 66, "devops", "coding", 1, 50, 15,
     "Create a feature branch, make commits, rebase on main, and submit a PR.", []),
    ("Git Conflict Resolution", 67, "devops", "debugging", 2, 100, 20,
     "Resolve a 3-way merge conflict in a feature branch and verify history.", [60]),
    ("Build Docker Image", 68, "devops", "coding", 2, 100, 25,
     "Write a multi-stage Dockerfile for a Python app with minimal image size.", []),
    ("Docker Compose Stack", 69, "devops", "coding", 3, 175, 35,
     "Orchestrate Django, PostgreSQL, and Redis with Docker Compose.", [62]),
    ("GitHub Actions CI", 70, "devops", "coding", 2, 100, 25,
     "Configure a GitHub Actions workflow that runs tests on every push.", [60]),
    ("Blue-Green Deployment", 71, "devops", "coding", 3, 175, 35,
     "Implement a blue-green deployment strategy with zero-downtime switchover.", [64]),
    ("Linux Process Management", 72, "devops", "coding", 1, 50, 15,
     "Use ps, top, kill, and systemctl to manage Linux processes.", []),
    ("Write Bash Deploy Script", 73, "devops", "coding", 2, 100, 25,
     "Write a bash script that deploys an app, runs migrations, and restarts services.", [66]),
    ("Deploy to Cloud", 74, "devops", "coding", 3, 175, 40,
     "Deploy a Docker Compose app to a cloud VM with environment configuration.", [63, 67]),
    ("Kubernetes Pod Deploy", 75, "devops", "coding", 4, 275, 50,
     "Deploy a Django app to Kubernetes with pods, services, and config maps.", [68]),

    # ── Family: debugging_testing (70-79) ────────────────────────────────────
    ("Debug Infinite Loop", 81, "debugging_testing", "debugging", 2, 100, 20,
     "Find and fix an infinite loop bug in a recursive function.", []),
    ("Fix Off-By-One Error", 85, "debugging_testing", "debugging", 2, 100, 15,
     "Identify and fix an off-by-one error in a loop boundary condition.", []),
    ("Debug Memory Leak", 82, "debugging_testing", "debugging", 4, 275, 40,
     "Profile a Python app to find and fix a memory leak caused by circular refs.", [70]),
    ("Write Pytest Suite", 83, "debugging_testing", "coding", 2, 100, 25,
     "Write a complete pytest test suite for a Calculator class with edge cases.", []),
    ("TDD Red-Green-Refactor", 84, "debugging_testing", "coding", 3, 175, 35,
     "Build a Stack class using TDD: write failing tests first, then implement.", [73]),
    ("Fix Race Condition", 86, "debugging_testing", "debugging", 3, 175, 35,
     "Debug a race condition in a multi-threaded counter and apply locking.", [70]),
    ("Test Edge Cases", 85, "debugging_testing", "coding", 2, 100, 20,
     "Write boundary-value tests for a function handling empty, null, and max inputs.", []),
    ("Mock External API", 83, "debugging_testing", "coding", 3, 175, 30,
     "Write tests that mock HTTP calls to external APIs using unittest.mock.", [73]),
    ("Debug Stack Overflow", 81, "debugging_testing", "debugging", 3, 175, 25,
     "Fix a recursive function that causes a stack overflow on large inputs.", [70]),
    ("Integration Test Suite", 84, "debugging_testing", "coding", 3, 175, 35,
     "Write integration tests for a Django REST API endpoint with database fixtures.", [74]),

    # ── Family: product_ux (80-89) ───────────────────────────────────────────
    ("Design Navigation Menu", 88, "product_ux", "coding", 1, 50, 15,
     "Build a responsive navigation menu with dropdowns and mobile hamburger.", []),
    ("Create Visual Hierarchy", 89, "product_ux", "coding", 2, 100, 20,
     "Redesign a flat page layout using typography scale and whitespace hierarchy.", [80]),
    ("ARIA Labels Audit", 90, "product_ux", "coding", 2, 100, 20,
     "Audit a web page for accessibility and add proper ARIA labels and roles.", [80]),
    ("Screen Reader Testing", 91, "product_ux", "coding", 3, 175, 30,
     "Optimize a form component for screen reader navigation and announcements.", [82]),
    ("Micro-Animation Feedback", 92, "product_ux", "coding", 2, 100, 25,
     "Add micro-animations to button clicks and form submissions for user feedback.", [80]),
    ("Optimize Animation FPS", 93, "product_ux", "coding", 3, 175, 30,
     "Refactor CSS animations to use transform/opacity and achieve 60fps.", [84]),
    ("Design Responsive Layout", 94, "product_ux", "coding", 2, 100, 25,
     "Build a mobile-first responsive page with fluid grid and breakpoint variants.", [80]),
    ("Build Adaptive Card", 95, "product_ux", "coding", 3, 175, 30,
     "Create a card component that adapts layout and content across screen sizes.", [86]),
    ("Map User Onboarding Flow", 96, "product_ux", "coding", 2, 100, 25,
     "Design and document a 5-step user onboarding flow with progress indicator.", [80]),
    ("A/B Test Landing Page", 97, "product_ux", "coding", 3, 175, 35,
     "Set up an A/B test comparing two landing page variants with conversion tracking.", [88]),

    # ── Family: fullstack_integration (90-99) ────────────────────────────────
    ("REST API Design Review", 40, "fullstack_integration", "mcq", 3, 175, 20,
     "Evaluate REST API designs for proper HTTP methods, status codes, and naming.", []),
    ("Database Migration Script", 47, "fullstack_integration", "coding", 2, 100, 25,
     "Write a Django migration that adds a new field with a data migration.", []),
    ("Redis Session Store", 58, "fullstack_integration", "coding", 3, 175, 30,
     "Configure Django to use Redis as a session backend and cache store.", [52]),
    ("Celery Task Pipeline", 59, "fullstack_integration", "coding", 3, 175, 35,
     "Build a Celery task chain: validate → process → notify with error handling.", [53]),
    ("Docker Dev Environment", 69, "fullstack_integration", "coding", 3, 175, 30,
     "Create a Docker Compose dev environment with hot-reload for Django and React.", [63]),
    ("API Rate Limit Test", 65, "fullstack_integration", "coding", 3, 175, 30,
     "Write load tests for a rate-limited API endpoint and verify throttle behavior.", [59]),
    ("End-to-End Auth Flow", 41, "fullstack_integration", "coding", 3, 175, 40,
     "Build a complete signup → login → token refresh → protected route flow.", [38]),
    ("Monitoring Dashboard", 63, "fullstack_integration", "coding", 2, 100, 30,
     "Build a Grafana dashboard with key metrics from Prometheus instrumentation.", [57]),
    ("Full System Health Check", 55, "fullstack_integration", "coding", 2, 100, 20,
     "Implement a /health endpoint that checks DB, Redis, and Celery connectivity.", []),
    ("Production Checklist Review", 76, "fullstack_integration", "mcq", 5, 400, 30,
     "Review a production deployment checklist covering security, scaling, and monitoring.", [98]),
]
