# Generated by Django 5.2.13 on 2026-04-30 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0002_initial'),
        ('quests', '0011_remove_solutioncomment_quests_solu_solutio_5093d8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executiontask',
            name='task_id',
            field=models.CharField(help_text='Celery task UUID', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='executiontask',
            name='worker_node',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='executiontask',
            index=models.Index(fields=['submission', 'status'], name='exectask_submission_status_idx'),
        ),
        migrations.AddIndex(
            model_name='executiontask',
            index=models.Index(fields=['task_id'], name='exectask_task_id_idx'),
        ),
        migrations.AddIndex(
            model_name='executiontask',
            index=models.Index(fields=['worker_node', 'status'], name='exectask_worker_status_idx'),
        ),
        migrations.AddIndex(
            model_name='executiontask',
            index=models.Index(fields=['-created_at'], name='exectask_created_at_idx'),
        ),
    ]
