# Generated by Django 5.2.13 on 2026-04-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('coding', 'Coding'), ('debugging', 'Debugging'), ('mcq', 'Multiple Choice')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starter_code', models.TextField(blank=True, default='')),
                ('test_cases', models.JSONField(default=list)),
                ('xp_reward', models.IntegerField(default=0)),
                ('estimated_minutes', models.IntegerField(default=15)),
                ('difficulty_multiplier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('java', 'Java'), ('go', 'Go')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('flagged', 'Flagged'), ('explanation_provided', 'Explanation Provided')], default='pending', max_length=20)),
                ('execution_result', models.JSONField(default=dict)),
                ('ai_feedback', models.JSONField(default=dict)),
                ('ai_detection_score', models.FloatField(default=0.0)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
