# Generated by Django 6.0.4 on 2026-04-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('flagged', 'Flagged'), ('explanation_provided', 'Explanation Provided'), ('approved', 'Approved'), ('confirmed_ai', 'Confirmed AI')], default='pending', max_length=20),
        ),
    ]
