# Generated by Django 5.2.13 on 2026-04-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_sharedsolution_solutioncomment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sharedsolution',
            new_name='quests_shar_shared__8ebf1b_idx',
            old_name='quests_shar_shared_idx',
        ),
        migrations.RenameIndex(
            model_name='solutioncomment',
            new_name='quests_solu_solutio_5093d8_idx',
            old_name='quests_solu_solutio_idx',
        ),
        migrations.RenameIndex(
            model_name='solutioncomment',
            new_name='quests_solu_author__690567_idx',
            old_name='quests_solu_author_idx',
        ),
    ]
