# Generated by Django 5.2.13 on 2026-04-28 11:18

from django.db import migrations

def populate_quests(apps, schema_editor):
    Quest = apps.get_model('quests', 'Quest')
    Skill = apps.get_model('skills', 'Skill')

    def safe_create(**kwargs):
        title = kwargs.pop('title')
        Quest.objects.get_or_create(title=title, defaults=kwargs)

    """
    SkillTree AI - Sample Quest Data Population Script
    Adds test quests across all skill categories with real test cases.

    Usage:
        python manage.py shell < scripts/populate_quests.py
    """


    print("Clearing existing quests...")
    # Quest.objects.all().delete()

    # Helper to get skill safely
    def get_skill(title):
        try:
            return Skill.objects.get(title=title)
        except Skill.DoesNotExist:
            print(f"  ⚠ Skill '{title}' not found — run populate_skills.py first")
            return None

    # ── Python / Arrays ──────────────────────────────────────────────────────────

    arrays = get_skill("Arrays & Lists")
    python_skill = get_skill("Python Programming")
    binary_search_skill = get_skill("Binary Search")
    sorting_skill = get_skill("Sorting Algorithms")
    dp_skill = get_skill("Dynamic Programming")
    linked_list_skill = get_skill("Linked Lists")
    stacks_skill = get_skill("Stacks & Queues")
    trees_skill = get_skill("Binary Trees")
    js_skill = get_skill("JavaScript Fundamentals")

    if arrays:
        safe_create(
            skill=arrays,
            type='coding',
            title='Two Sum',
            description=(
                'Given an array of integers `nums` and an integer `target`, '
                'return the indices of the two numbers that add up to `target`.\n\n'
                'You may assume each input has exactly one solution.\n\n'
                'Example:\n'
                '  Input: nums = [2, 7, 11, 15], target = 9\n'
                '  Output: [0, 1]'
            ),
            starter_code=(
                'def two_sum(nums, target):\n'
                '    # Your solution here\n'
                '    pass\n\n'
                '# Read input\n'
                'import sys\n'
                'n = int(input())\n'
                'nums = list(map(int, input().split()))\n'
                'target = int(input())\n'
                'print(two_sum(nums, target))\n'
            ),
            test_cases=[
                {"input": "4\n2 7 11 15\n9",  "expected_output": "[0, 1]"},
                {"input": "3\n3 2 4\n6",       "expected_output": "[1, 2]"},
                {"input": "2\n3 3\n6",         "expected_output": "[0, 1]"},
            ],
            xp_reward=100,
            estimated_minutes=15,
            difficulty_multiplier=1.0,
        )

        safe_create(
            skill=arrays,
            type='coding',
            title='Maximum Subarray',
            description=(
                'Given an integer array `nums`, find the contiguous subarray '
                'with the largest sum and return its sum.\n\n'
                'Example:\n'
                '  Input: [-2, 1, -3, 4, -1, 2, 1, -5, 4]\n'
                '  Output: 6\n'
                '  Explanation: [4, -1, 2, 1] has the largest sum = 6.'
            ),
            starter_code=(
                'def max_subarray(nums):\n'
                '    # Your solution here (Kadane\'s algorithm)\n'
                '    pass\n\n'
                'nums = list(map(int, input().split()))\n'
                'print(max_subarray(nums))\n'
            ),
            test_cases=[
                {"input": "-2 1 -3 4 -1 2 1 -5 4", "expected_output": "6"},
                {"input": "1",                       "expected_output": "1"},
                {"input": "5 4 -1 7 8",             "expected_output": "23"},
            ],
            xp_reward=120,
            estimated_minutes=20,
            difficulty_multiplier=2.0,
        )

        safe_create(
            skill=arrays,
            type='debugging',
            title='Fix the Reverse Array',
            description=(
                'The function below is supposed to reverse an array in-place, '
                'but it has a bug. Find and fix it.\n\n'
                'Example:\n'
                '  Input: [1, 2, 3, 4, 5]\n'
                '  Output: [5, 4, 3, 2, 1]'
            ),
            starter_code=(
                'def reverse_array(nums):\n'
                '    left, right = 0, len(nums)\n'  # bug: should be len(nums) - 1
                '    while left < right:\n'
                '        nums[left], nums[right] = nums[right], nums[left]\n'
                '        left += 1\n'
                '        right -= 1\n'
                '    return nums\n\n'
                'nums = list(map(int, input().split()))\n'
                'print(reverse_array(nums))\n'
            ),
            test_cases=[
                {"input": "1 2 3 4 5", "expected_output": "[5, 4, 3, 2, 1]"},
                {"input": "1 2",       "expected_output": "[2, 1]"},
                {"input": "42",        "expected_output": "[42]"},
            ],
            xp_reward=80,
            estimated_minutes=10,
            difficulty_multiplier=1.0,
        )

    if python_skill:
        safe_create(
            skill=python_skill,
            type='coding',
            title='FizzBuzz',
            description=(
                'Print numbers from 1 to N.\n'
                'For multiples of 3 print "Fizz", for multiples of 5 print "Buzz", '
                'for multiples of both print "FizzBuzz".\n\n'
                'Example:\n'
                '  Input: 15\n'
                '  Output: 1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz'
            ),
            starter_code=(
                'def fizzbuzz(n):\n'
                '    result = []\n'
                '    # Your solution here\n'
                '    return result\n\n'
                'n = int(input())\n'
                'print(" ".join(str(x) for x in fizzbuzz(n)))\n'
            ),
            test_cases=[
                {"input": "15", "expected_output": "1 2 Fizz 4 Buzz Fizz 7 8 Fizz Buzz 11 Fizz 13 14 FizzBuzz"},
                {"input": "5",  "expected_output": "1 2 Fizz 4 Buzz"},
                {"input": "1",  "expected_output": "1"},
            ],
            xp_reward=50,
            estimated_minutes=10,
            difficulty_multiplier=1.0,
        )

        safe_create(
            skill=python_skill,
            type='coding',
            title='Palindrome Check',
            description=(
                'Write a function that returns True if a string is a palindrome, False otherwise.\n'
                'Ignore case and non-alphanumeric characters.\n\n'
                'Example:\n'
                '  Input: "A man a plan a canal Panama"\n'
                '  Output: True'
            ),
            starter_code=(
                'def is_palindrome(s):\n'
                '    # Your solution here\n'
                '    pass\n\n'
                's = input()\n'
                'print(is_palindrome(s))\n'
            ),
            test_cases=[
                {"input": "A man a plan a canal Panama", "expected_output": "True"},
                {"input": "race a car",                  "expected_output": "False"},
                {"input": "Was it a car or a cat I saw", "expected_output": "True"},
            ],
            xp_reward=75,
            estimated_minutes=15,
            difficulty_multiplier=1.0,
        )

        safe_create(
            skill=python_skill,
            type='mcq',
            title='Python Data Types Quiz',
            description=(
                'Which of the following is an immutable data type in Python?\n\n'
                'A) list\n'
                'B) dict\n'
                'C) tuple\n'
                'D) set\n\n'
                'Enter the letter of your answer (A, B, C, or D).'
            ),
            starter_code='print(input())\n',
            test_cases=[
                {"input": "C", "expected_output": "C"},
            ],
            xp_reward=30,
            estimated_minutes=5,
            difficulty_multiplier=1.0,
        )

    if binary_search_skill:
        safe_create(
            skill=binary_search_skill,
            type='coding',
            title='Classic Binary Search',
            description=(
                'Given a sorted array of integers and a target value, '
                'return the index of the target. Return -1 if not found.\n\n'
                'Example:\n'
                '  Input: nums = [-1, 0, 3, 5, 9, 12], target = 9\n'
                '  Output: 4'
            ),
            starter_code=(
                'def binary_search(nums, target):\n'
                '    # Your solution here\n'
                '    pass\n\n'
                'n = int(input())\n'
                'nums = list(map(int, input().split()))\n'
                'target = int(input())\n'
                'print(binary_search(nums, target))\n'
            ),
            test_cases=[
                {"input": "6\n-1 0 3 5 9 12\n9",  "expected_output": "4"},
                {"input": "6\n-1 0 3 5 9 12\n2",  "expected_output": "-1"},
                {"input": "1\n5\n5",               "expected_output": "0"},
            ],
            xp_reward=150,
            estimated_minutes=20,
            difficulty_multiplier=2.0,
        )

        safe_create(
            skill=binary_search_skill,
            type='coding',
            title='Search Insert Position',
            description=(
                'Given a sorted array and a target, return the index if found. '
                'If not, return the index where it would be inserted in order.\n\n'
                'Example:\n'
                '  Input: [1, 3, 5, 6], target = 5 → Output: 2\n'
                '  Input: [1, 3, 5, 6], target = 2 → Output: 1'
            ),
            starter_code=(
                'def search_insert(nums, target):\n'
                '    # Your solution here\n'
                '    pass\n\n'
                'n = int(input())\n'
                'nums = list(map(int, input().split()))\n'
                'target = int(input())\n'
                'print(search_insert(nums, target))\n'
            ),
            test_cases=[
                {"input": "4\n1 3 5 6\n5", "expected_output": "2"},
                {"input": "4\n1 3 5 6\n2", "expected_output": "1"},
                {"input": "4\n1 3 5 6\n7", "expected_output": "4"},
            ],
            xp_reward=130,
            estimated_minutes=15,
            difficulty_multiplier=2.0,
        )

    if sorting_skill:
        safe_create(
            skill=sorting_skill,
            type='coding',
            title='Bubble Sort Implementation',
            description=(
                'Implement bubble sort to sort an array of integers in ascending order.\n\n'
                'Example:\n'
                '  Input: [64, 34, 25, 12, 22, 11, 90]\n'
                '  Output: [11, 12, 22, 25, 34, 64, 90]'
            ),
            starter_code=(
                'def bubble_sort(nums):\n'
                '    n = len(nums)\n'
                '    # Your solution here\n'
                '    return nums\n\n'
                'n = int(input())\n'
                'nums = list(map(int, input().split()))\n'
                'print(bubble_sort(nums))\n'
            ),
            test_cases=[
                {"input": "7\n64 34 25 12 22 11 90", "expected_output": "[11, 12, 22, 25, 34, 64, 90]"},
                {"input": "3\n3 1 2",                "expected_output": "[1, 2, 3]"},
                {"input": "1\n42",                   "expected_output": "[42]"},
            ],
            xp_reward=100,
            estimated_minutes=20,
            difficulty_multiplier=2.0,
        )

    if dp_skill:
        safe_create(
            skill=dp_skill,
            type='coding',
            title='Fibonacci with Memoization',
            description=(
                'Compute the Nth Fibonacci number using dynamic programming (memoization).\n\n'
                'F(0) = 0, F(1) = 1, F(n) = F(n-1) + F(n-2)\n\n'
                'Example:\n'
                '  Input: 10\n'
                '  Output: 55'
            ),
            starter_code=(
                'def fib(n, memo={}):\n'
                '    # Your solution here\n'
                '    pass\n\n'
                'n = int(input())\n'
                'print(fib(n))\n'
            ),
            test_cases=[
                {"input": "10", "expected_output": "55"},
                {"input": "0",  "expected_output": "0"},
                {"input": "1",  "expected_output": "1"},
                {"input": "20", "expected_output": "6765"},
            ],
            xp_reward=200,
            estimated_minutes=25,
            difficulty_multiplier=3.0,
        )

        safe_create(
            skill=dp_skill,
            type='coding',
            title='Climbing Stairs',
            description=(
                'You are climbing a staircase with N steps. '
                'Each time you can climb 1 or 2 steps. '
                'How many distinct ways can you reach the top?\n\n'
                'Example:\n'
                '  Input: 3\n'
                '  Output: 3\n'
                '  Explanation: 1+1+1, 1+2, 2+1'
            ),
            starter_code=(
                'def climb_stairs(n):\n'
                '    # Your solution here\n'
                '    pass\n\n'
                'n = int(input())\n'
                'print(climb_stairs(n))\n'
            ),
            test_cases=[
                {"input": "2", "expected_output": "2"},
                {"input": "3", "expected_output": "3"},
                {"input": "5", "expected_output": "8"},
            ],
            xp_reward=180,
            estimated_minutes=20,
            difficulty_multiplier=3.0,
        )

    if stacks_skill:
        safe_create(
            skill=stacks_skill,
            type='coding',
            title='Valid Parentheses',
            description=(
                'Given a string containing only "(", ")", "{", "}", "[", "]", '
                'determine if the input string is valid.\n\n'
                'A string is valid if:\n'
                '- Open brackets are closed by the same type\n'
                '- Open brackets are closed in the correct order\n\n'
                'Example:\n'
                '  Input: "()[]{}" → Output: True\n'
                '  Input: "(]"     → Output: False'
            ),
            starter_code=(
                'def is_valid(s):\n'
                '    # Your solution here (use a stack)\n'
                '    pass\n\n'
                's = input()\n'
                'print(is_valid(s))\n'
            ),
            test_cases=[
                {"input": "()[]{}",  "expected_output": "True"},
                {"input": "(]",      "expected_output": "False"},
                {"input": "{[]}",    "expected_output": "True"},
                {"input": "([)]",    "expected_output": "False"},
            ],
            xp_reward=150,
            estimated_minutes=20,
            difficulty_multiplier=2.0,
        )

    if linked_list_skill:
        safe_create(
            skill=linked_list_skill,
            type='coding',
            title='Reverse a Linked List',
            description=(
                'Given the head of a singly linked list, reverse it and return the new head.\n\n'
                'For this problem, represent the list as space-separated integers.\n\n'
                'Example:\n'
                '  Input: 1 2 3 4 5\n'
                '  Output: 5 4 3 2 1'
            ),
            starter_code=(
                'class ListNode:\n'
                '    def __init__(self, val=0, nxt=None):\n'
                '        self.val = val\n'
                '        self.next = nxt\n\n'
                'def reverse_list(head):\n'
                '    # Your solution here\n'
                '    pass\n\n'
                'def build(vals):\n'
                '    dummy = ListNode()\n'
                '    cur = dummy\n'
                '    for v in vals:\n'
                '        cur.next = ListNode(v)\n'
                '        cur = cur.next\n'
                '    return dummy.next\n\n'
                'def to_list(head):\n'
                '    res = []\n'
                '    while head:\n'
                '        res.append(head.val)\n'
                '        head = head.next\n'
                '    return res\n\n'
                'vals = list(map(int, input().split()))\n'
                'head = build(vals)\n'
                'print(" ".join(map(str, to_list(reverse_list(head)))))\n'
            ),
            test_cases=[
                {"input": "1 2 3 4 5", "expected_output": "5 4 3 2 1"},
                {"input": "1 2",       "expected_output": "2 1"},
                {"input": "1",         "expected_output": "1"},
            ],
            xp_reward=160,
            estimated_minutes=25,
            difficulty_multiplier=2.0,
        )

    if trees_skill:
        safe_create(
            skill=trees_skill,
            type='coding',
            title='Maximum Depth of Binary Tree',
            description=(
                'Given the root of a binary tree, return its maximum depth.\n\n'
                'The maximum depth is the number of nodes along the longest path '
                'from the root node down to the farthest leaf node.\n\n'
                'Input format: level-order traversal, "null" for missing nodes.\n\n'
                'Example:\n'
                '  Input: 3 9 20 null null 15 7\n'
                '  Output: 3'
            ),
            starter_code=(
                'from collections import deque\n\n'
                'class TreeNode:\n'
                '    def __init__(self, val=0, left=None, right=None):\n'
                '        self.val = val\n'
                '        self.left = left\n'
                '        self.right = right\n\n'
                'def max_depth(root):\n'
                '    # Your solution here\n'
                '    pass\n\n'
                'def build(vals):\n'
                '    if not vals or vals[0] == "null": return None\n'
                '    root = TreeNode(int(vals[0]))\n'
                '    q = deque([root])\n'
                '    i = 1\n'
                '    while q and i < len(vals):\n'
                '        node = q.popleft()\n'
                '        if i < len(vals) and vals[i] != "null":\n'
                '            node.left = TreeNode(int(vals[i]))\n'
                '            q.append(node.left)\n'
                '        i += 1\n'
                '        if i < len(vals) and vals[i] != "null":\n'
                '            node.right = TreeNode(int(vals[i]))\n'
                '            q.append(node.right)\n'
                '        i += 1\n'
                '    return root\n\n'
                'vals = input().split()\n'
                'root = build(vals)\n'
                'print(max_depth(root))\n'
            ),
            test_cases=[
                {"input": "3 9 20 null null 15 7", "expected_output": "3"},
                {"input": "1 null 2",              "expected_output": "2"},
                {"input": "1",                     "expected_output": "1"},
            ],
            xp_reward=175,
            estimated_minutes=25,
            difficulty_multiplier=3.0,
        )

    if js_skill:
        safe_create(
            skill=js_skill,
            type='coding',
            title='Sum of Array (JavaScript)',
            description=(
                'Write a JavaScript function that returns the sum of all numbers in an array.\n\n'
                'Example:\n'
                '  Input: [1, 2, 3, 4, 5]\n'
                '  Output: 15'
            ),
            starter_code=(
                'function sumArray(nums) {\n'
                '  // Your solution here\n'
                '}\n\n'
                'const nums = require("fs").readFileSync("/dev/stdin","utf8").trim().split(" ").map(Number);\n'
                'console.log(sumArray(nums));\n'
            ),
            test_cases=[
                {"input": "1 2 3 4 5", "expected_output": "15"},
                {"input": "10 20",     "expected_output": "30"},
                {"input": "0",         "expected_output": "0"},
            ],
            xp_reward=80,
            estimated_minutes=10,
            difficulty_multiplier=1.0,
        )

    total = Quest.objects.count()
    print(f"\n✅ Created {total} quests successfully!")
    print("\nQuests by type:")
    for t in ['coding', 'debugging', 'mcq']:
        count = Quest.objects.filter(type=t).count()
        print(f"   - {t}: {count}")
    print("\nQuests by difficulty:")
    for d in [1.0, 2.0, 3.0, 4.0]:
        count = Quest.objects.filter(difficulty_multiplier=d).count()
        if count:
            print(f"   - Level {int(d)}: {count}")


def reverse_populate_quests(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_rename_quests_shar_shared_idx_quests_shar_shared__8ebf1b_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_quests, reverse_populate_quests),
    ]
