# Generated by Django 6.0.4 on 2026-04-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0008_add_celery_task_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='questsubmission',
            new_name='quests_ques_celery__c1e7e4_idx',
            old_name='quests_quest_celery_task_id_idx',
        ),
    ]
