# Generated by Django 5.2.13 on 2026-04-30 11:03

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0010_add_is_stub_field'),
        ('skills', '0004_embeddingrecord_remove_skill_skill_depth_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='solutioncomment',
            name='quests_solu_solutio_5093d8_idx',
        ),
        migrations.RenameIndex(
            model_name='questsubmission',
            new_name='submission_user_quest_idx',
            old_name='quests_ques_user_id_8e1e84_idx',
        ),
        migrations.RenameIndex(
            model_name='questsubmission',
            new_name='submission_celery_task_idx',
            old_name='quests_ques_celery__c1e7e4_idx',
        ),
        migrations.RenameIndex(
            model_name='sharedsolution',
            new_name='sharedsol_shared_at_idx',
            old_name='quests_shar_shared__8ebf1b_idx',
        ),
        migrations.RenameIndex(
            model_name='solutioncomment',
            new_name='comment_author_idx',
            old_name='quests_solu_author__690567_idx',
        ),
        migrations.AddField(
            model_name='quest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='is_stub',
            field=models.BooleanField(default=False, help_text='True if generated stub — QuestAutoFillService will populate content.'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='test_cases',
            field=models.JSONField(default=list, help_text='List of {input, expected_output} dicts. For MCQ: [{expected_output: <int 0-3>}].'),
        ),
        migrations.AlterField(
            model_name='questsubmission',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('flagged', 'Flagged'), ('explanation_provided', 'Explanation Provided'), ('approved', 'Approved'), ('confirmed_ai', 'Confirmed AI')], default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['skill', 'type', 'is_stub'], name='quest_skill_type_stub_idx'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['-created_at'], name='quest_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='questsubmission',
            index=models.Index(fields=['user', 'status', '-created_at'], name='submission_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedsolution',
            index=models.Index(fields=['submission'], name='sharedsol_submission_idx'),
        ),
        migrations.AddIndex(
            model_name='solutioncomment',
            index=models.Index(fields=['solution', 'parent', 'created_at'], name='comment_solution_thread_idx'),
        ),
    ]
