# Generated by Django 6.0.4 on 2026-07-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0011_remove_solutioncomment_quests_solu_solutio_5093d8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='type',
            field=models.CharField(choices=[('coding', 'Coding'), ('debugging', 'Debugging'), ('mcq', 'Multiple Choice'), ('exercise', 'Practical Exercise'), ('challenge', 'Mini Challenge')], max_length=20),
        ),
    ]
