# Generated by Django 5.2.13 on 2026-04-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_score', models.FloatField(default=0.0)),
                ('llm_score', models.FloatField(default=0.0)),
                ('heuristic_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('llm_reasoning', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
