# Generated by Django 5.2.13 on 2026-04-24 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_detection', '0001_initial'),
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlog',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_logs', to='quests.questsubmission'),
        ),
    ]
