# Generated by Django 5.2.13 on 2026-04-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_detection', '0002_initial'),
        ('quests', '0011_remove_solutioncomment_quests_solu_solutio_5093d8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlog',
            name='embedding_score',
            field=models.FloatField(default=0.0, help_text='Vector similarity score (0-1)'),
        ),
        migrations.AlterField(
            model_name='detectionlog',
            name='final_score',
            field=models.FloatField(default=0.0, help_text='Weighted combination (0-1)'),
        ),
        migrations.AlterField(
            model_name='detectionlog',
            name='heuristic_score',
            field=models.FloatField(default=0.0, help_text='Rule-based heuristic score (0-1)'),
        ),
        migrations.AlterField(
            model_name='detectionlog',
            name='llm_reasoning',
            field=models.JSONField(default=dict, help_text='Detailed LLM decision breakdown'),
        ),
        migrations.AlterField(
            model_name='detectionlog',
            name='llm_score',
            field=models.FloatField(default=0.0, help_text='LLM-based detection score (0-1)'),
        ),
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['submission', '-analyzed_at'], name='detectionlog_submission_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['final_score', '-analyzed_at'], name='detectionlog_score_idx'),
        ),
    ]
