# Generated by Django 5.2.13 on 2026-04-30 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0003_initial'),
        ('quests', '0011_remove_solutioncomment_quests_solu_solutio_5093d8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participants', to='multiplayer.match'),
        ),
        migrations.AlterField(
            model_name='matchparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'quest'], name='match_status_quest_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['winner'], name='match_winner_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['-created_at'], name='match_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='matchparticipant',
            index=models.Index(fields=['user', '-joined_at'], name='matchpart_user_joined_idx'),
        ),
        migrations.AddIndex(
            model_name='matchparticipant',
            index=models.Index(fields=['match', '-score'], name='matchpart_match_score_idx'),
        ),
    ]
