# Generated by Django 6.0.4 on 2026-04-25 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_xplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_goal', models.CharField(choices=[('job_prep', 'Job Preparation'), ('interview', 'Interview Cracker'), ('upskill', 'Upskilling'), ('passion', 'Passion Project')], max_length=20)),
                ('target_role', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField(default=0)),
                ('category_levels', models.JSONField(default=dict)),
                ('selected_interests', models.JSONField(default=list)),
                ('weekly_hours', models.IntegerField(default=5)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path_generated', models.BooleanField(default=False)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
