# Generated by Django 6.0.4 on 2026-04-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_onboarding_generated_fields'),
        ('users', '0003_onboardingprofile'),
    ]

    operations = [
    ]
