# Generated by Django 5.2.13 on 2026-04-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20260427_1226'),
        ('users', '0006_badges'),
    ]

    operations = [
    ]
