# Generated by Django 5.2.13 on 2026-04-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_0003_studygroup_0006_badges'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adaptiveprofile',
            new_name='users_adapt_user_id_cd99c1_idx',
            old_name='users_adapt_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='adaptiveprofile',
            new_name='users_adapt_ability_d87e8a_idx',
            old_name='users_adapt_ability_idx',
        ),
        migrations.RenameIndex(
            model_name='adaptiveprofile',
            new_name='users_adapt_preferr_a3229f_idx',
            old_name='users_adapt_diff_idx',
        ),
        migrations.RenameIndex(
            model_name='badge',
            new_name='users_badge_slug_b47f34_idx',
            old_name='users_badge_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='badge',
            new_name='users_badge_rarity_809657_idx',
            old_name='users_badge_rarity_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroup',
            new_name='users_study_invite__3a4a68_idx',
            old_name='users_study_invite__idx',
        ),
        migrations.RenameIndex(
            model_name='studygroup',
            new_name='users_study_created_6efe05_idx',
            old_name='users_study_created__idx',
        ),
        migrations.RenameIndex(
            model_name='studygroupgoal',
            new_name='users_study_group_i_d0355b_idx',
            old_name='users_study_group_t_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroupgoal',
            new_name='users_study_skill_i_8779f5_idx',
            old_name='users_study_skill_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroupmembership',
            new_name='users_study_group_i_a5e92a_idx',
            old_name='users_study_group_u_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroupmembership',
            new_name='users_study_user_id_fdc0dc_idx',
            old_name='users_study_user_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroupmessage',
            new_name='users_study_group_i_807204_idx',
            old_name='users_study_group_s_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroupmessage',
            new_name='users_study_sender__64caf8_idx',
            old_name='users_study_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='userbadge',
            new_name='users_userb_user_id_223787_idx',
            old_name='users_userbadge_user_seen_idx',
        ),
        migrations.RenameIndex(
            model_name='userbadge',
            new_name='users_userb_badge_i_501b76_idx',
            old_name='users_userbadge_badge_idx',
        ),
        migrations.RenameIndex(
            model_name='userskillflag',
            new_name='users_users_user_id_dfab3c_idx',
            old_name='users_userskill_user_flag_idx',
        ),
        migrations.RenameIndex(
            model_name='userskillflag',
            new_name='users_users_skill_i_44c59b_idx',
            old_name='users_userskill_skill_flag_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyreport',
            new_name='users_weekl_user_id_b5aa64_idx',
            old_name='users_weekl_user_id_generated_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyreport',
            new_name='users_weekl_week_nu_71a54b_idx',
            old_name='users_weekl_week_nu_year_idx',
        ),
        migrations.AlterField(
            model_name='userskillflag',
            name='reason',
            field=models.TextField(blank=True, default='', help_text="Reason for flagging (e.g., 'Consecutive failures: 3')"),
        ),
    ]
