# Generated by Django 5.2.13 on 2026-04-28 13:07

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_fix_weeklyreport_year_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingprofile',
            name='generated_topic',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='onboardingprofile',
            name='generated_tree_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='year',
            field=models.IntegerField(default=users.models.get_current_year),
        ),
    ]
