# Generated by Django 5.2.13 on 2026-04-30 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0011_remove_solutioncomment_quests_solu_solutio_5093d8_idx_and_more'),
        ('skills', '0004_embeddingrecord_remove_skill_skill_depth_idx_and_more'),
        ('users', '0010_onboardingprofile_generated_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_before', models.FloatField()),
                ('ability_after', models.FloatField()),
                ('difficulty_before', models.IntegerField()),
                ('difficulty_after', models.IntegerField()),
                ('reason', models.CharField(help_text='e.g. "Consecutive failures: 3" or "Streak: 7 days"', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='adaptiveprofile',
            name='users_adapt_user_id_cd99c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='xplog',
            name='users_xplog_user_id_99a258_idx',
        ),
        migrations.RenameIndex(
            model_name='adaptiveprofile',
            new_name='adaptive_ability_idx',
            old_name='users_adapt_ability_d87e8a_idx',
        ),
        migrations.RenameIndex(
            model_name='adaptiveprofile',
            new_name='adaptive_difficulty_idx',
            old_name='users_adapt_preferr_a3229f_idx',
        ),
        migrations.RenameIndex(
            model_name='badge',
            new_name='badge_slug_idx',
            old_name='users_badge_slug_b47f34_idx',
        ),
        migrations.RenameIndex(
            model_name='badge',
            new_name='badge_rarity_idx',
            old_name='users_badge_rarity_809657_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroup',
            new_name='studygroup_code_idx',
            old_name='users_study_invite__3a4a68_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroup',
            new_name='studygroup_creator_idx',
            old_name='users_study_created_6efe05_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroupgoal',
            new_name='groupgoal_group_date_idx',
            old_name='users_study_group_i_d0355b_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroupgoal',
            new_name='groupgoal_skill_idx',
            old_name='users_study_skill_i_8779f5_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroupmembership',
            new_name='membership_group_user_idx',
            old_name='users_study_group_i_a5e92a_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroupmembership',
            new_name='membership_user_idx',
            old_name='users_study_user_id_fdc0dc_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroupmessage',
            new_name='groupmsg_group_sent_idx',
            old_name='users_study_group_i_807204_idx',
        ),
        migrations.RenameIndex(
            model_name='studygroupmessage',
            new_name='groupmsg_sender_idx',
            old_name='users_study_sender__64caf8_idx',
        ),
        migrations.RenameIndex(
            model_name='userbadge',
            new_name='userbadge_user_seen_idx',
            old_name='users_userb_user_id_223787_idx',
        ),
        migrations.RenameIndex(
            model_name='userbadge',
            new_name='userbadge_badge_idx',
            old_name='users_userb_badge_i_501b76_idx',
        ),
        migrations.RenameIndex(
            model_name='userskillflag',
            new_name='userskillflag_user_flag_idx',
            old_name='users_users_user_id_dfab3c_idx',
        ),
        migrations.RenameIndex(
            model_name='userskillflag',
            new_name='userskillflag_skill_flag_idx',
            old_name='users_users_skill_i_44c59b_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyreport',
            new_name='weeklyreport_user_idx',
            old_name='users_weekl_user_id_b5aa64_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklyreport',
            new_name='weeklyreport_week_idx',
            old_name='users_weekl_week_nu_71a54b_idx',
        ),
        migrations.RemoveField(
            model_name='adaptiveprofile',
            name='adjustment_history',
        ),
        migrations.RemoveField(
            model_name='onboardingprofile',
            name='generated_tree_id',
        ),
        migrations.AddField(
            model_name='onboardingprofile',
            name='generated_tree',
            field=models.ForeignKey(blank=True, help_text='The AI-generated skill tree created during onboarding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_profiles', to='skills.generatedskilltree'),
        ),
        migrations.AlterField(
            model_name='adaptiveprofile',
            name='ability_score',
            field=models.FloatField(default=0.5, help_text='0.0 (struggling) to 1.0 (advanced). Updated via Bayesian formula.'),
        ),
        migrations.AlterField(
            model_name='adaptiveprofile',
            name='last_adjusted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adaptiveprofile',
            name='preferred_difficulty',
            field=models.IntegerField(default=3, help_text='Auto-set to ceil(ability_score × 5). Range 1-5.'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='unlock_condition',
            field=models.JSONField(default=dict, help_text='Structured unlock condition — see docstring for schema.'),
        ),
        migrations.AlterField(
            model_name='userskillflag',
            name='flag',
            field=models.CharField(choices=[('too_easy', 'Too Easy'), ('struggling', 'Struggling'), ('mastered', 'Mastered')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userskillflag',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='pdf_path',
            field=models.CharField(blank=True, default='', help_text='Relative path to generated PDF under MEDIA_ROOT. Empty if PDF not yet generated.', max_length=500),
        ),
        migrations.AlterField(
            model_name='xplog',
            name='source',
            field=models.CharField(help_text='e.g. "Quest: Python Basics"', max_length=200),
        ),
        migrations.AddIndex(
            model_name='onboardingprofile',
            index=models.Index(fields=['user'], name='onboarding_user_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingprofile',
            index=models.Index(fields=['generated_tree', 'path_generated'], name='onboarding_tree_status_idx'),
        ),
        migrations.AddIndex(
            model_name='xplog',
            index=models.Index(fields=['user', '-created_at'], name='xplog_user_created_idx'),
        ),
        migrations.AddField(
            model_name='adaptiveadjustmentlog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_logs', to='users.adaptiveprofile'),
        ),
        migrations.AddField(
            model_name='adaptiveadjustmentlog',
            name='quest',
            field=models.ForeignKey(blank=True, help_text='The quest that triggered this adjustment (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptive_adjustments', to='quests.quest'),
        ),
        migrations.AddIndex(
            model_name='adaptiveadjustmentlog',
            index=models.Index(fields=['profile', '-created_at'], name='adaptlog_profile_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptiveadjustmentlog',
            index=models.Index(fields=['quest'], name='adaptlog_quest_idx'),
        ),
    ]
