# Generated by Django 5.2.13 on 2026-05-19 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_badge_system_fixes'),
        ('users', '0011_adaptiveadjustmentlog_and_more'),
    ]

    operations = [
    ]
